os: Visual Studio 2022
# Based off https://github.com/VoidStarKat/appveyor-rust/blob/master/appveyor.yml
# Caching from https://vadosware.io/post/faster-ci-builds-for-rust-with-builder-images-and-sccache/
# and https://rustprojectprimer.com/building/cache.html
cache:
    - C:\Users\appveyor\.rustup
    - C:\Users\appveyor\.cargo
    - C:\Users\appveyor\sccache
    
environment:
  SCCACHE_DIR: C:\Users\appveyor\sccache
  RUSTC_WRAPPER: sccache

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - cargo install sccache
    - rustc -vV
    - cargo -vV
  
build_script:
    - git clone --depth=1 https://codeberg.org/voltagex/gram
    - cd gram && cargo build --release
